Water Quality Analysis for MKE



```{r}
# library(remotes)
# remotes::install_github("DOI-USGS/dataRetrieval",
#                build_vignettes = TRUE)
# install.packages("dataRetrieval")
library(dataRetrieval)
library(dplyr)

# get_data <- function(x){
#   readWQPsummary(statecode = x,
#                  sampleMedia = "Water",
#                  characteristicName = "Phosphorus",
#                  siteType = "Stream",
#                  providers = "NWIS") |> 
#     mutate(state = x)
# }

state_cd <- "WI"

 df_summary <- readWQPsummary(
   statecode = state_cd,
   sampleMedia = "Water",
   providers = "NWIS"
   )

# df_summary

```

```{r}
filter_data <- df_summary |> 
    rename(site = MonitoringLocationIdentifier) |> 
    mutate(Lat = as.numeric(MonitoringLocationLatitude),
           Lon = as.numeric(MonitoringLocationLongitude)) |> 
    group_by(site, CharacteristicName) |> 
  #site, Lat, Lon, StateName
    summarise(min_year = min(YearSummarized),
              max_year = max(YearSummarized),
              count = sum(ResultCount)) |> 
    mutate(POR = max_year - min_year) |> 
    filter(count > 200,
           POR >= 15) |>
    ungroup() |> 
    filter(max_year >= 2016) |>
    arrange(desc(count))

filter_data

# CharacteristicName: "Phosphorus", "pH", "Temperature, water", "Total suspended solids", "Total dissolved solids"
```


```{r}
# find WI stations with a few of the desired characteristic names
sites <- filter_data |>
  filter(CharacteristicName=="Phosphorus") |>
  select(site) |>
  distinct() #|>
  # head(20)
# sites



wi_data <- readWQPdata(
 siteid = sites$site,
  # siteid = "USGS-423329088323300",
                       # sites$site
                       #"USGS-423329088323300"
                  characteristicName = "Phosphorus",
                  # startDateLo = "1995-01-01",
                  # startDateHi = "2020-12-31",
                  sampleMedia = "Water",
                  ignore_attributes = TRUE)

```


```{r}
library(lubridate)

selected_wi_data <- wi_data |>
  select(
    Location_Identifier,
    Location_Name,
    Location_Type,
    Location_State,
    Location_CountyName,
    Location_Latitude,
    Location_Longitude,
    Location_HUCEightDigitCode,
    Location_HUCTwelveDigitCode,
    Activity_TypeCode,
    Activity_Media,
    Activity_DepthHeightMeasure,
    Activity_DepthHeightMeasureUnit,
    Result_Characteristic,
    Result_SampleFraction,
    Result_MeasureIdentifier,
    Result_Measure,
    Result_MeasureUnit,
    Result_MeasureType,
    Result_CharacteristicGroup,
    Activity_StartTimeZone_offset,
    Activity_StartDateTime,
    Activity_StartDate
  ) |>
    filter(Result_Measure<10) |>
    # filter(Result_Measure<=100) |>
    filter(Activity_StartDate>="2000-01-01") |>
    # filter(Location_Type=="Lake, Reservoir, Impoundment") |>
    mutate(
         year=lubridate::year(Activity_StartDate),
         month=lubridate::month(Activity_StartDate),
         month_year = format(Activity_StartDate, "%Y-%m")
         ) |>
    group_by(year, month) |>
    mutate(monthly_average = mean(Result_Measure)) |>
    ungroup() |>
    arrange(desc(year), desc(month))

selected_wi_data
# summary(selected_wi_data)
```


```{r}
library(ggplot2)
culer = c(rgb(.12,.67,.85,.7), rgb(.67,.12,.85,.7))

ggplot(data = selected_wi_data) +
  geom_point(aes(x = Activity_StartDate,
                 y = Result_Measure), color = culer[1]) +
  geom_line(aes(x=Activity_StartDate,
                y=monthly_average), color = culer[2]) +
  xlab("Date") +
  ylab("Phosphorus [mg/l as P]") +
  labs(title = "Daily and Monthly Phosphorus levels in WI Water")

# ggplot(data = dv) +
#   dataRetrieval_timeseries_framework() +
#   geom_line(aes(
#     x = Date,
#     y = X_00060_00003)) +
#   xlab("Date") +
#   labs(title = attr(dv, "siteInfo")$station_nm,
#        caption = paste("Data pulled on:", 
#                        as.Date(attr(dv, "queryTime")))) +
#   ylab(unescape_html(attr(dv, "variableInfo")$variableName))
```


```{r}
# Bois d'Arc Creek near Honey Grove, TX -----------------------------------

##                  Gage No.;      Param. Codes;               Start & End date 
rawBAC = readNWISdv("07332622", c("00060", "00010", "00300"), "2016-06-01", "2024-06-01") #Discharge

BAC = addWaterYear(rawBAC) #Adds the correct water year column

names(BAC)[7] = "Q_cfs"# Adds a name to our new column
names(BAC)[5] = "waterT"
names(BAC)[9] = "DO"

rm(rawBAC)


newBAC <- BAC |>
    mutate(
      year=lubridate::year(Date),
      month=lubridate::month(Date)
      ) |>
    group_by(year, month) |>
    mutate(monthly_average = mean(waterT)) |>
    ungroup()
newBAC

culer = c(rgb(.12,.67,.85,.7), rgb(.67,.12,.85,.7))
# BAC
ggplot(BAC, aes(x = Date, y = Q_cfs)) +
  geom_line()

ggplot(newBAC, aes(x = Date, y = waterT)) +
  geom_line(color=culer[1]) +
  geom_line(aes(x = Date, y = monthly_average), color="red") +
  xlab("Date") +
  ylab("Water Temperature [degrees celcius]") 

ggplot(BAC, aes(x = Date, y = DO)) +
  geom_line() 
```



```{r}
as.data.frame(colSums(is.na(wi_data)))
# summary(wi_data)
# Location_Identifier
# Location_Name
# Location_Type
# Location_State
# Location_CountyName	
# Location_Latitude
# Location_Longitude
# Location_HUCEightDigitCode
# Location_HUCTwelveDigitCode
# Activity_TypeCode
# Activity_Media
# Activity_DepthHeightMeasure
# Activity_DepthHeightMeasureUnit
# Result_Characteristic
# Result_SampleFraction
# Result_MeasureIdentifier
# Result_Measure
# Result_MeasureUnit
# Result_MeasureType
# Result_CharacteristicGroup
# Activity_StartTimeZone_offset
# Activity_StartDateTime
```


```{r}
# 
# # Load packages
# library(dataRetrieval)
# library(dplyr)
# 
# # state code information for the 48 conterminous United States plus DC:
# state_cd_cont <- stateCd[c(2,4:12,14:52),]
# state_cd_cont
# rownames(state_cd_cont) <- seq(length=nrow(state_cd_cont)) # reset row sequence
# 
# for(i in seq_len(nrow(state_cd_cont))){
#   
#   state_cd <- state_cd_cont$STATE[i]
#   state_nm <- state_cd_cont$STUSAB[i]
#   message("Getting: ", state_nm)
#   
#   df_summary <- tryCatch({
#     readWQPsummary(statecode = state_cd,
#                    sampleMedia = "Water",
#                    providers = "NWIS",
#                    CharacteristicName = "pH"
#                    )
#   }, 
#   error=function(cond) {
#     message(paste("No data in:", state_nm))
#     break()
#   })
#   
#   sites <- df_summary |> 
#     filter(YearSummarized >= 1995,
#            YearSummarized <= 2020) |> 
#     group_by(MonitoringLocationIdentifier, MonitoringLocationName, Provider) |> 
#     summarise(start_year = min(YearSummarized, na.rm = TRUE),
#               end_year = max(YearSummarized, na.rm = TRUE),
#               count_activity = sum(ActivityCount, na.rm = TRUE),
#               count_result = sum(ResultCount, na.rm = TRUE)) |> 
#     ungroup() |> 
#     filter(count_activity >= 40)
#   
#   if(nrow(sites) > 0){
#     df_state <- tryCatch({
#       readWQPdata(siteid = sites$MonitoringLocationIdentifier,
#                   CharacteristicName = "pH",
#                   startDateLo = "1995-01-01",
#                   startDateHi = "2023-12-31",
#                   sampleMedia = "Water", 
#                   convertType = FALSE,
#                   ignore_attributes = TRUE
#       )
#     }, 
#     error=function(cond) {
#       message(paste("No data in:", state_nm))
#     })
#     
#     if(nrow(df_state) > 0){
#       # I would write the data here, just in case:
#       saveRDS(df_state, file = paste(state_nm, "data.rds", 
#                                      sep = "_"))
#       
#     } else {
#       message("No data in:", state_nm)
#     }
#   }
# }


```



```{r}

# all_nitrogen <- data.frame()
# # for(state in stateCd$STUSAB){
# for(state in state_cd_cont$STUSAB){
#   
#   state_df <- tryCatch({
#     readRDS(paste0(state, "_data.rds"))
#   }, error = function(e) e)
#     
#     
#   if(!inherits(state_df, "error") && nrow(state_df) > 0){
#     df_slim <- state_df |>
#       filter(ActivityMediaSubdivisionName %in% c("Surface Water") |
#                is.na(ActivityMediaSubdivisionName),
#              ResultSampleFractionText %in% c("Total")) 
#     
#     all_nitrogen <- bind_rows(all_nitrogen, df_slim)
#   }
# 
# }
# 
# all_nitrogen <- parse_WQP(all_nitrogen)
# all_nitrogen <- dataRetrieval:::create_WQP_attributes(all_nitrogen,
#                         siteid = unique(all_nitrogen$MonitoringLocationIdentifier))

```

